### ISSUE TITLE
ER_NOT_ALLOWED_COMMAND

### ISSUE THREAD

**Issue by victor0801x** [MariaDB/mariadb-connector-nodejs#22]
when setting the `permitLocalInfile: true` and the `pipelining: true` at the same time, `LOAD DATE INFILE` command will not allow

**Comment by rusher** [comment]
Command "LOAD LOCAL INFILE" will result in a new exchange between connector and server.  
This is the only case in [protocol](https://mariadb.com/kb/en/library/clientserver-protocol/).

Connector when having finish sending a command and permitLocalInfile set to false can immediately send another command since the server will handle the command in order, and TCP guaranty FIFO order. 

So those 2 options are incompatible. 
if set together, this results having permitLocalInfile set to false.

If needing a connection with "LOAD LOCAL INFILE" enable, you cannot set option pipelining. 
Still, an error would be a better solution than silently changing the value of permitLocalInfile to false.

**Comment by victor0801x** [comment]
thanks for reply
close it

**Comment by victor0801x** [comment]
the latest version `2.0.2` still silently change `permitLocalInfile` to false
when option `pipelining` is `true`

should console.warn() or throw error ?
```js
this.pipelining = opts.pipelining || true;
this.permitLocalInfile = opts.permitLocalInfile || false;
if (this.pipelining && this.permitLocalInfile) {
  console.warn(...);
  this.permitLocalInfile = false;
}
```

**Comment by rusher** [comment]
corrected with https://github.com/MariaDB/mariadb-connector-nodejs/commit/f4cb72785c7a7e7ead40ea7ec65fb7d49a86b0f0
