### ISSUE TITLE
Default date/time/timezone handling

### ISSUE THREAD

**Issue by magnusjt** [MariaDB/mariadb-connector-nodejs#33]
Thanks for your work on this library! I haven't used it yet, but it looks interesting.

I'm wondering how dates, times, and timezones are handled by default in this project. In my experience, people tend to stick with the defaults (at least until the bugs start to show up), so it's important that they are sane. The existing mysql libs don't do a good job here. In my opinion, the defaults should be:

1. Dates and datetimes are returned as string (as opposed to Date objects) since they do not have timezone info
2. Timestamps should be parsed as UTC and returned as Date objects. This works because of the next point:
3. The mysql session timezone should be set to UTC by default ("SET time_zone='+00:00';")

What do you think?

**Comment by knoxcard** [comment]
Use sequelize as your database ORM.

https://github.com/sequelize/sequelize/pull/10705

**Comment by rusher** [comment]
@magnusjt 
The current solution seems the most suitable in terms of ease of use but is based on having client and server configured according to the same timezone.

Handling client and server following different timezone is complex, the solution you describe would work well. The problem then would be letting user parsing timestamps and date string themselves, opening the door to mistakes. 
I don't see any excellent solution, particulary because javascript doesn't have DATE / TIMESTAMP distinction, only [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object

**Comment by knoxcard** [comment]
Close issue?

**Comment by magnusjt** [comment]
@knoxcard I personally don't use sequelize, or any other orm's, so can't benefit from their fix

@rusher "The problem then would be letting user parsing timestamps and date string themselves, opening the door to mistakes." - The mistake would be to parse them using Date, imo..

The ease of use argument is fair, but will inevitably lead to bugs for many people. Maybe it's just a question of making this clear in the documentation, and easy to configure for different time zone on client and server?

**Comment by rusher** [comment]
Documentation never hurt. 
I'll do that shortly, then post here reference for review/ideas.

**Comment by knoxcard** [comment]
Guess this issue can be closed now, after the most recent release?

**Comment by rusher** [comment]
better to keep it open as a reminder !

**Comment by knoxcard** [comment]
should we carry this over to JIRA and merge it with the other (similar) issue?

(Think this has been resolved already?)

**Comment by rusher** [comment]
closing, not an issue, but task, created as https://jira.mariadb.org/browse/CONJS-82
