### ISSUE TITLE
Reset command not permitted for server

### ISSUE THREAD

**Issue by db-developer** [MariaDB/mariadb-connector-nodejs#69]
This happens to pooled and standalone connections.
I'm not really used to mariadb (10.1.14) and RESET described by mariadb docs seems to apply to clustered connections, which does not match mariadb-connectors description for reset. 

A hint on how to resolve the following error would be helpful. Thanx
ConnectionOptions are minimal: user/password/database - that's it.
`
Received: [Error: Reset command not permitted for server [object Object]]

      420 |         try  { await connection.reset(); }
      421 |         catch( err ) { error = err; }
      422 |         expect( error ).toBeNull();  <<<<<
`

**Comment by knoxcard** [comment]
https://mariadb.com/kb/en/library/reset/

Do you have **RELOAD** privilege?

**Comment by db-developer** [comment]
`
> SHOW GRANTS FOR 'test'@'localhost'
   GRANT USAGE ON *.* TO 'test'@'localhost' IDENTIFIED BY PASSWORD '****************'
   GRANT ALL PRIVILEGES ON `test`.* TO 'test'@'localhost'
`
I guess that should do the trick, but I fear this is the wrong track.

Compare both
https://mariadb.com/kb/en/library/connector-nodejs-promise-api/#connectionreset-promise
https://mariadb.com/kb/en/library/reset/

connectionreset-promise !== reset

**Comment by knoxcard** [comment]
@db-developer - so it worked?

**Comment by db-developer** [comment]
No. Not yet.
But maybe it's a misunderstanding of  GRANT ALL PRIVILEGES on my side... RELOAD might not be included in "ALL PRIVILEGES" because it's a global privilege and not a database privilege. My bad.
Have to check that later ... thanks

**Comment by db-developer** [comment]
No. No change.

SHOW GRANTS FOR 'test'@'localhost'
GRANT RELOAD ON *.* TO 'test'@'localhost' IDENTIFIED BY PASSWORD '*************'
GRANT ALL PRIVILEGES ON `test`.* TO 'test'@'localhost'

Received: [Error: Reset command not permitted for server [object Object]]

**Comment by knoxcard** [comment]
@rusher - any thoughts?

**Comment by rusher** [comment]
This relies on a protocol command [COM_RESET_CONNECTION](https://mariadb.com/kb/en/library/com_reset_connection/) (!= SQL command) that exist in MariaDB since version 10.2.4 and in MySQL since 5.7.3. 
If the server doesn't match requirement, the function returns a promise with error "Reset command not permitted for server XXX". 
 
So, this won't work for MariaDB server 10.1.14.
I'll update [documentation](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionreset--promise) to indicate that. 

For MariaDB 10.1.14, the only possibility to reset connection is to call [connection.changeUser](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionchangeuseroptions--promise) function using the same user. Change user command basically only keep the socket, but reauthenticate and reinitialize all connection. That's a lot more than reset, but that works too. 

Btw there is some workaround to make that works for all MariaDB version: use  I'll add this to the next version.

**Comment by rusher** [comment]
Another precision about the use of reset: When giving back a connection to a pool, reset will be called if server version allows it. That can be disabled with option `resetAfterUse`. 

Documentation addition has been done: https://github.com/MariaDB/mariadb-connector-nodejs/commit/993003bdc2a05a201c35e7195ab32a25526b692d , and rejection message is changed to indicate server minimum version requirement

**Comment by rusher** [comment]
closing since message is corrected. 
Feel free to open another issue link to this one if you think of anything else.

**Comment by db-developer** [comment]
`Received: [Error: Reset command not permitted for server [object Object] (requires server MariaDB version 10.2.4+ or MySQL 5.7.3+)]`

Works like charme. Thanx.
