### ISSUE TITLE
Escape sql string

### ISSUE THREAD

**Issue by mhf-ir** [MariaDB/mariadb-connector-nodejs#79]
Like: https://github.com/mysqljs/mysql#escaping-query-values
How to string escape ? not in connection.query. just process string.

**Comment by rusher** [comment]
The following [mysql](https://github.com/mysqljs/mysql/blob/master/lib/Connection.js) function: 
- escape
- escapeId
- format
are the only not implemented function compare to mysql API. 

Mainly because I've not seen the use case. 
If you have any use cases, please share, and I will gladly implement it. 
 
`escapeId` may have some interest, following https://mariadb.com/kb/en/library/identifier-names/ rules to escape '`' characters and add beginning and ending '`' only when needed.

**Comment by mhf-ir** [comment]
Think about simple query builder for make sql base on request or any conditional ways.
Simple use case:
```js
let mainQuery = 'SELECT * FROM t1';
const whereFields = [];
if (req.query.foo) {
   whereFields.push(`foo = ${myEscapefunc(req.query.foo)}`);
}
if (req.query.bar) {
   whereFields.push(`foo = ${myEscapefunc(req.query.bar)}`);
}
if (updateFields.length) {
   mainQuery = `${mainQuery} WHERE ${whereFields.join(' AND ')}`;
}
```

**Comment by knoxcard** [comment]
I just use Sequelize, it does it for you. 


```
$ npm install --save sequelize 
$ npm install --save mariadb
```

**Comment by mhf-ir** [comment]
I dont want to use orm.
All db clients (like PHP PDO) has this feature. It's essential.

**Comment by rusher** [comment]
My point is that i can see use of `escapeId` so table names/columns can be properly escaped, '🌟`s' => '`🌟\`s`'

The connector is streaming data to socket buffer to avoid using a lot of memory. I would prefer always to always have query build with question mark placeholder to better behavior, like, in the use-case you describe, it would make sense to write it like : 
```
let mainQuery = 'SELECT * FROM t1';
const whereFields = [];
const params = [];
if (req.query.foo) {
   whereFields.push(`foo = ?`);
   params.push(req.query.foo);
}
if (req.query.bar) {
   whereFields.push(`bar = ?`);
   params.push(req.query.bar);
}
if (updateFields.length) {
   mainQuery = `${mainQuery} WHERE ${whereFields.join(' AND ')}`;
}
conn.query(mainQuery, params)
  .then(rows => {
...
```

Connector won't use those methods, because they are limited : 
* doesn't permit streaming
* string concatenation can take lot of time for big string (and memory)
* doesn't permit Stream object. 

But that permit to construct query, so that alright, with those limitation. And that can easyly be documented. 
Alright, that will be on next 2.2 release

**Comment by mhf-ir** [comment]
Thanks for added escape :heart:
